// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM0HabTVFEIOUvOUczYbNefnn4gnvf8qw',
    appId: '1:169970862562:web:d8d7b37b27744ff43b51bb',
    messagingSenderId: '169970862562',
    projectId: 'syarahapp-cecd0',
    authDomain: 'syarahapp-cecd0.firebaseapp.com',
    storageBucket: 'syarahapp-cecd0.appspot.com',
    measurementId: 'G-4VT1L5VNRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhz80TUM9YbcAPY9KFg2acTi2luYVztyw',
    appId: '1:169970862562:android:4b8a4eef8521438a3b51bb',
    messagingSenderId: '169970862562',
    projectId: 'syarahapp-cecd0',
    storageBucket: 'syarahapp-cecd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCviqzhc7pTmrV9oy9HoYGZSACpmhSR8Ic',
    appId: '1:169970862562:ios:7ec31f93ce088fab3b51bb',
    messagingSenderId: '169970862562',
    projectId: 'syarahapp-cecd0',
    storageBucket: 'syarahapp-cecd0.appspot.com',
    iosBundleId: 'com.example.sayarah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCviqzhc7pTmrV9oy9HoYGZSACpmhSR8Ic',
    appId: '1:169970862562:ios:a6ddfc5cfb8087923b51bb',
    messagingSenderId: '169970862562',
    projectId: 'syarahapp-cecd0',
    storageBucket: 'syarahapp-cecd0.appspot.com',
    iosBundleId: 'com.example.sayarah.RunnerTests',
  );
}
